# Generated by Django 5.1.15 on 2026-09-24 10:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import inspections.clock
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=inspections.clock.Clock.now)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoadGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(default=inspections.clock.Clock.now)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CleaningContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=inspections.clock.Clock.now)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='inspections.contractor')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='inspections.roadgrid')),
            ],
            options={
                'ordering': ['grid_id', 'valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.CharField(choices=[('open', '待整改'), ('rectified', '已整改')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField()),
                ('rectified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=inspections.clock.Clock.now)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_duplicates', to='inspections.event')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inspections.roadgrid')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, '基础扣分'), (1, '逾期一级(24h)'), (2, '逾期二级(48h)'), (3, '逾期三级(72h)')])),
                ('reason', models.CharField(max_length=300)),
                ('base_points', models.IntegerField()),
                ('escalation_points', models.IntegerField(default=0)),
                ('rule_version', models.CharField(default='v1', max_length=32)),
                ('contractor_locked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('provisional', '待复核'), ('locked', '复核锁定'), ('appealed', '申诉更正')], default='provisional', max_length=16)),
                ('issued_at', models.DateTimeField(default=inspections.clock.Clock.now)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalty_units', to='inspections.contractor')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_units', to='inspections.event')),
                ('liable_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalty_units', to='inspections.cleaningcontract')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_points', models.IntegerField(help_text='正数追加扣分，负数退还/撤销扣分，最终扣分=原值+所有更正之和')),
                ('reason', models.CharField(max_length=500)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=inspections.clock.Clock.now)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='inspections.penaltyunit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('phash', models.CharField(db_index=True, max_length=16)),
                ('taken_at', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('kind', models.CharField(choices=[('problem', '问题照片'), ('rectify', '整改照片')], default='problem', max_length=16)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=inspections.clock.Clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='inspections.event')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='inspections.roadgrid')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamming_distance', models.PositiveSmallIntegerField()),
                ('distance_meters', models.FloatField()),
                ('time_gap_seconds', models.FloatField()),
                ('within_spatial_window', models.BooleanField()),
                ('within_temporal_window', models.BooleanField()),
                ('decision', models.CharField(choices=[('pending', '待人工判定'), ('same_event', '确认同一事件(不同角度)'), ('different_place', '相似但不同地点')], default='pending', max_length=20)),
                ('decided_by', models.CharField(blank=True, max_length=100)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=inspections.clock.Clock.now)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_pairs', to='inspections.photo')),
                ('similar_photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_pairs_reverse', to='inspections.photo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Rectification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_at', models.DateTimeField()),
                ('effective', models.BooleanField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=inspections.clock.Clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rectifications', to='inspections.event')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rectification_evidence', to='inspections.photo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='penaltyunit',
            constraint=models.UniqueConstraint(fields=('event', 'level'), name='uniq_penalty_event_level'),
        ),
        migrations.AddConstraint(
            model_name='duplicatecandidate',
            constraint=models.UniqueConstraint(fields=('photo', 'similar_photo'), name='uniq_candidate_photo_pair'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['taken_at'], name='inspections_taken_a_0bc6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='inspections_status_f52f20_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['opened_at'], name='inspections_opened__d646e6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['merged_into'], name='inspections_merged__8704d8_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningcontract',
            index=models.Index(fields=['grid', 'valid_from'], name='inspections_grid_id_e458b7_idx'),
        ),
    ]
