# Generated by Django 5.1.15 on 2026-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='phash',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
